In [147]:
import pandas as pd
df = pd.read_csv('miRNAexpressiontestclincle1.csv')
df.head()

,hsa-let-7a-1,hsa-let-7a-2,hsa-let-7a-3,hsa-let-7b,hsa-let-7c,hsa-let-7d,hsa-let-7e,hsa-let-7f-1,hsa-let-7f-2,hsa-let-7g,...,hsa-mir-942,hsa-mir-943,hsa-mir-944,hsa-mir-95,hsa-mir-96,hsa-mir-98,hsa-mir-99a,hsa-mir-99b,Survival,SurvivalStatus
0,12.5118,13.5062,12.5058,13.1423,9.4597,9.1296,11.3277,4.5361,13.1852,8.7630,...,2.4290,0.0000,7.0844,4.4115,3.2474,5.8341,7.7704,14.8284,3.353388,0
1,12.8151,13.8253,12.8277,13.0250,8.0617,9.6969,9.6906,4.6816,14.1684,9.4817,...,4.3008,0.2781,9.5068,1.5428,5.5523,6.5335,5.1035,14.0989,12.788901,1
2,13.9389,14.9395,13.9522,14.2588,8.8684,9.0935,10.8985,5.9200,14.9715,10.4961,...,4.1204,0.0000,8.7194,4.2529,4.5285,6.3210,4.7599,14.2215,42.344741,0
3,13.7992,14.8060,13.8097,14.8904,11.5533,9.5417,9.7590,4.8165,13.8766,9.4976,...,3.2618,0.0000,7.5526,2.5631,5.6962,6.5749,8.7677,13.6794,8.153335,0
4,13.6592,14.6622,13.6761,14.4914,9.4091,9.2256,9.4294,6.3407,13.8757,9.8671,...,4.7225,0.0000,7.6184,2.6753,4.1333,5.6403,6.3945,13.7741,23.835355,0

In [148]:
from lifelines import CoxPHFitter


df.isnull().sum()

hsa-let-7a-1      0
hsa-let-7a-2      0
hsa-let-7a-3      0
hsa-let-7b        0
hsa-let-7c        0
                 ..
hsa-mir-98        0
hsa-mir-99a       0
hsa-mir-99b       0
Survival          0
SurvivalStatus    0
Length: 844, dtype: int64

In [128]:
Y=df.days

In [146]:
from lifelines import CoxPHFitter
from lifelines.datasets import load_rossi
cph = CoxPHFitter(penalizer=0.4)
cph.fit(df, duration_col='days', event_col='survivalstatus')
cph.print_summary()  # access the individual results using cph.summary

<lifelines.CoxPHFitter: fitted with 19 total observations, 13 right-censored observations>
             duration col = 'days'
                event col = 'survivalstatus'
                penalizer = 0.4
                 l1 ratio = 0.0
      baseline estimation = breslow
   number of observations = 19
number of events observed = 6
   partial log-likelihood = -13.11
         time fit was run = 2023-12-10 22:14:16 UTC

---
               coef  exp(coef)   se(coef)   coef lower 95%   coef upper 95%  exp(coef) lower 95%  exp(coef) upper 95%
covariate
hsa-let-7a-1  -0.05       0.95       0.56            -1.15             1.05                 0.32                 2.85
hsa-let-7a-2  -0.05       0.95       0.56            -1.14             1.04                 0.32                 2.84
hsa-let-7a-3  -0.06       0.94       0.56            -1.16             1.04                 0.31                 2.83
hsa-let-7b     0.00       1.00       0.45            -0.88             0.89                 0.41                 2.43
hsa-let-7c     0.01       1.01       0.19            -0.36             0.38                 0.70                 1.47
hsa-let-7d     0.26       1.30       0.58            -0.86             1.39                 0.42                 4.02
hsa-let-7e     0.27       1.31       0.31            -0.35             0.88                 0.71                 2.42
hsa-let-7f-1  -0.30       0.74       0.39            -1.06             0.46                 0.35                 1.59
hsa-let-7f-2   0.00       1.00       0.34            -0.66             0.66                 0.52                 1.94
hsa-let-7g     0.08       1.09       0.48            -0.86             1.03                 0.42                 2.81

               cmp to     z    p   -log2(p)
covariate
hsa-let-7a-1     0.00 -0.09 0.93       0.11
hsa-let-7a-2     0.00 -0.09 0.93       0.10
hsa-let-7a-3     0.00 -0.10 0.92       0.12
hsa-let-7b       0.00  0.01 0.99       0.01
hsa-let-7c       0.00  0.07 0.94       0.09
hsa-let-7d       0.00  0.46 0.65       0.63
hsa-let-7e       0.00  0.85 0.40       1.34
hsa-let-7f-1     0.00 -0.77 0.44       1.17
hsa-let-7f-2     0.00  0.00 1.00       0.00
hsa-let-7g       0.00  0.18 0.86       0.22
---
Concordance = 0.75
Partial AIC = 46.23
log-likelihood ratio test = 1.49 on 10 df
-log2(p) of ll-ratio test = 0.00

In [149]:
from scipy import stats